workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: 1.21.0-1.0.pre
      xcode: 12.0.1
      cocoapods: default
    scripts:
      - flutter packages pub get
      - &iPhone_11
        name: Start iPhone 11 and take screens
        script: |
          xcrun simctl shutdown all
          TEST_DEVICE=$(xcrun simctl create test-device com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-0)
          xcrun simctl boot $TEST_DEVICE
          flutter drive -t test_driver/app.dart
          cd /Users/builder/exported_artefacts/test && mv myscreenshot1.png iPhone_11.png
      - &iPhone_7_Plus
        name: &Start iPhone 7 Plus and take screens
        script: |
          xcrun simctl shutdown all
          TEST_DEVICE=$(xcrun simctl create test-device com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus com.apple.CoreSimulator.SimRuntime.iOS-13-0)
          xcrun simctl boot $TEST_DEVICE
          flutter drive -t test_driver/app.dart
          cd /Users/builder/exported_artefacts/test && mv myscreenshot1.png iPhone_7_Plus.png
      - &iPad_Pro_2nd_gen
        name: &Start iPad Pro (12.9-inch) (2nd generation) and take screens
        script: |
          xcrun simctl shutdown all
          TEST_DEVICE=$(xcrun simctl create test_device com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation- com.apple.CoreSimulator.SimRuntime.iOS-13-0)
          xcrun simctl boot $TEST_DEVICE
          flutter drive -t test_driver/app.dart
          cd /Users/builder/exported_artefacts/test && mv myscreenshot1.png iPad_Pro_2nd_gen.png
      - &iPad_Pro_3rd_gen
        name: &Start iPad Pro (12.9-inch) (3rd generation) and take screens
        script: |
          xcrun simctl shutdown all
          TEST_DEVICE=$(xcrun simctl create test_device com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---3rd-generation- com.apple.CoreSimulator.SimRuntime.iOS-13-0)
          xcrun simctl boot $TEST_DEVICE
          flutter drive -t test_driver/app.dart
          cd /Users/builder/exported_artefacts/test && mv myscreenshot1.png iPad_Pro_3rd_gen.png
    artifacts:
      - flutter_drive.log
  second-workflow:
    name: Second Workflow
    max_build_duration: 60
    environment:
      flutter: 1.21.0-1.0.pre
      xcode: 12.0.1
      cocoapods: default
    scripts:
      - flutter packages pub get
      - *iPhone_11
      - *iPhone_7_Plus
      - *iPad_Pro_2nd_gen
      - *iPad_Pro_3rd_gen
    artifacts:
      - flutter_drive.log
