workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      flutter: 1.21.0-1.0.pre
      xcode: 12.0.1
      cocoapods: default
    scripts:
      - flutter packages pub get
      - &iPhone_7
        name: Start iPhone 7 and take screens
        script: |
          xcrun simctl shutdown all
          TEST_DEVICE=$(xcrun simctl create test-device com.apple.CoreSimulator.SimDeviceType.iPhone-7 com.apple.CoreSimulator.SimRuntime.iOS-13-0)
          xcrun simctl boot $TEST_DEVICE
          flutter drive -t test_driver/app.dart
          cd /Users/builder/exported_artefacts/test && mv myscreenshot1.png iPhone_7.png
      - &iPad_Air_2
        name: &Start iPad Air 2 and take screens
        script: |
          xcrun simctl shutdown all
          TEST_DEVICE=$(xcrun simctl create test-device com.apple.CoreSimulator.SimDeviceType.iPad-Air-2 com.apple.CoreSimulator.SimRuntime.iOS-13-7)
          xcrun simctl boot $TEST_DEVICE
          flutter drive -t test_driver/app.dart
          cd /Users/builder/exported_artefacts/test && mv myscreenshot1.png iPad_Air_2.png
    artifacts:
      - flutter_drive.log
  second-workflow:
    name: Second Workflow
    max_build_duration: 60
    environment:
      flutter: 1.21.0-1.0.pre
      xcode: 12.0.1
      cocoapods: default
    scripts:
      - flutter packages pub get
      - *iPhone_7
      - *iPad_Air_2
    artifacts:
      - flutter_drive.log
