workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 60
    environment:
      groups:
        - meow
      vars:
        RANDOM: 'boo'
    scripts:
      - echo $MAGIC
      - sleep 100
